language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install coveralls"
  - "pip install coverage"
  - "pip install pytest-cov"
  - "python setup.py develop"
script:
  coverage run --source pretex -m py.test
after_success:
  coveralls
notifications:
  email: false