language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install coveralls"
  - "pip install pytest-cov"
  - "python setup.py develop"
script:
  py.test --cov tests/test_main.py
after_success:
  coveralls
notifications:
  email: false